// tools/vitest-matrix/config/C4-jsdom-forks-narrow-g.ts
// Auto-generated by tools/scripts/seed-vitest-variants.cjs
import { defineConfig } from 'vitest/config';
export default defineConfig({
  test: {
    environment: 'jsdom',
    environmentOptions: { jsdom: { url: 'http://localhost' } },
    include: ['specs/**/*.spec.{ts,tsx}', 'src/**/*.spec.{ts,tsx}'],
    exclude: ['**/*.e2e.*','web-e2e/**','api-e2e/**','apps/**','packages/**','shared/**','node_modules','dist','build','coverage'],
    globals: true,
    pool: 'forks',
    isolate: true,
    setupFiles: ['test/setup-tests.ts']
  },
  esbuild: { jsx: 'automatic' },
  resolve: { alias: { '@': 'C:/Users/kashi/Desktop/COS/careeros/web/src' } },
});
