name: Activity logging guard

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: activity-guard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: 'true'
      NX_DAEMON: 'false'
      NX_NO_CLOUD: 'true'
      NEXT_TELEMETRY_DISABLED: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Prisma prepare
        run: |
          pnpm -F ./apps/api run prisma:format
          pnpm -F ./apps/api run prisma:validate
          pnpm -F ./apps/api run prisma:generate

      - name: Verify activity contract
        run: pnpm run check:activity
