name: Activity E2E

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: activity-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install
        run: pnpm -w install --frozen-lockfile

      # Validate schema early (optional, but useful)
      - name: Prisma format/validate
        run: |
          pnpm -w exec prisma format --schema=apps/api/prisma/schema.prisma
          pnpm -w exec prisma validate --schema=apps/api/prisma/schema.prisma

      # ✅ Generate BEFORE build so TS has @prisma/client available
      - name: Generate Prisma Client
        run: pnpm -w run generate:prisma

      - name: Build
        run: pnpm -w build

      # Playwright is common in E2E; keep if you use it (harmless otherwise)
      - name: Install Playwright (if used)
        run: pnpm -w exec playwright install --with-deps || true

      # Debug to confirm cwd & paths
      - name: Debug CWD and prisma path
        run: |
          echo "CWD=$(pwd)"
          ls -la
          ls -la apps/api/prisma || true

      # Run E2E from repo root so relative --schema paths resolve
      - name: Run E2E
        working-directory: ${{ github.workspace }}
        env:
          PRISMA_SCHEMA: apps/api/prisma/schema.prisma
        run: pnpm -w run e2e

      - name: Upload Playwright traces (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trace
          if-no-files-found: ignore
          retention-days: 7
          path: |
            playwright-report/**
            **/playwright/**/trace.zip
