name: Activity Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Run runtime activity check
        run: pnpm run ci:check:activity
