name: Activity CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  activity:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      # If needed:
      # - run: pnpm -w exec prisma generate
      # - run: pnpm run db:migrate

      - name: Serve (prod) → wait → seed+verify (strict)
        run: pnpm run ci:web:prod

      - name: Upload activity report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: activity-ci-report
          path: activity-ci-report.json
          if-no-files-found: warn
