name: Activity E2E
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: activity-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm -w install
      
      - name: Generate Prisma Client
        run: pnpm -w exec prisma generate --schema=apps/api/prisma/schema.prisma

      # Always run on PRs (dev mode)
      - name: Activity CI (dev)
        run: pnpm -w run ci:web

      # Only run on pushes to main (prod mode)
      - name: Activity CI (prod)
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') }}
        run: pnpm -w run ci:web:prod
