name: Activity logging guard

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: activity-guard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Verify activity contract
        run: pnpm run check:activity
