name: CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**'            # ensure PRs always trigger
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

# Avoid “cancelled” loops; one run per PR or ref
concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    name: build_test            # <- required check context: "CI / build_test"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: 'true'
      NX_DAEMON: 'false'        # avoid Nx daemon flakiness in CI
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prisma Client generation
        shell: bash
        run: |
          set -euxo pipefail
          mapfile -t SCHEMAS < <(git ls-files | grep -E '/prisma/schema\.prisma$' || true)
          if [ ${#SCHEMAS[@]} -eq 0 ]; then
            echo "No prisma/schema.prisma files found; skipping prisma generate"
            exit 0
          fi
          pnpm exec prisma -v
          for S in "${SCHEMAS[@]}"; do
            echo "→ Generating Prisma Client for: $S"
            pnpm exec prisma generate --schema="$S"
          done

      - name: Typecheck
        run: pnpm -w tsc -b

      - name: Guard missing router imports
        run: node tools/scripts/check-router-imports.cjs

      - name: Build all (Nx)
        run: pnpm -w exec nx run-many -t build --all --skip-nx-cache --exclude=root

      - name: API tests
        run: pnpm -w exec nx run api:test --skip-nx-cache

      - name: Web tests
        run: pnpm -w exec nx run web:test --skip-nx-cache

      - name: Repo health scan
        run: node tools/scripts/scan-repo-health.cjs --log-dir tools/logs || true

      - name: Assert clean working tree
        run: node tools/scripts/ci-assert-clean.cjs
