name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  workflow_dispatch:

# Make the required check name stable:  "CI / build_test"
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    # Don’t run for draft PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prisma Client generation
        shell: bash
        run: |
          set -euxo pipefail
          # Find every prisma/schema.prisma in the repo (monorepo-safe)
          mapfile -t SCHEMAS < <(git ls-files | grep -E '/prisma/schema\.prisma$' || true)
          if [ ${#SCHEMAS[@]} -eq 0 ]; then
            echo "No prisma/schema.prisma files found; skipping prisma generate"
            exit 0
          fi
          pnpm dlx prisma -v
          for S in "${SCHEMAS[@]}"; do
            echo "→ Generating Prisma Client for: $S"
            pnpm dlx prisma generate --schema="$S"
          done

      - name: Typecheck
        run: pnpm -w tsc -b

      - name: Guard missing router imports
        run: node tools/scripts/check-router-imports.cjs

      - name: Build all (Nx)
        run: pnpm -w exec nx run-many -t build --all --skip-nx-cache --exclude=root

      - name: API tests
        run: npx nx run api:test --skip-nx-cache
        # If there's no "api" target, comment this step out or make it conditional.

      - name: Web tests
        run: npx nx run web:test --skip-nx-cache

      - name: Repo health scan
        run: node tools/scripts/scan-repo-health.cjs --log-dir tools/logs

      - name: Assert clean working tree
        run: node tools/scripts/ci-assert-clean.cjs

      - name: Prisma enum checker (dry-run)
        run: node tools/scripts/fix-prisma-enums.cjs --glob "apps/api/src/**/*.ts" --dry
