name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pnpm -w install

      - name: Final repo scan
        run: pnpm run scan:final

      - name: Phase 3 module scan
        run: pnpm run scan:modules

      - name: Stub report (non-blocking)
        run: pnpm run scan:stubs

      - name: Stub report (non-blocking)
        run: pnpm run scan:stubs

      - name: Stub gate (enforce after deadline)
        run: pnpm run scan:stubs -- --fail-after=2025-10-01


      - name: Web tests
        run: pnpm run test:web

      - name: Upload scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scans-and-module-reports
          path: |
            scans/**
            tools/module-scan-output/**
          if-no-files-found: ignore
