name: release-on-tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read
  issues: write

concurrency:
  group: release-on-tag-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      NX_DAEMON: 'false'
      NX_NO_CLOUD: 'true'
      NEXT_TELEMETRY_DISABLED: '1'
      TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # Your one-liner that typechecks, builds, tests, and runs final scans
      - name: Build + Test + Final Scan
        run: pnpm run release:prep

      - name: Upload scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scans-${{ env.TAG }}
          path: |
            scans/**
            tools/logs/**
          if-no-files-found: warn
          retention-days: 7

      - name: Generate release notes
        run: node tools/scripts/gen-release-notes.cjs "${{ env.TAG }}" > RELEASE_NOTES.md

      - name: Create/Update GitHub Release + Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body_path: RELEASE_NOTES.md
          make_latest: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            scans/**/*.json
            tools/logs/**/*.json
